import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Nushu } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const notoNushu = Noto_Sans_Nushu({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-mono"
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AppProvider } from "@/lib/context";
import { ThemeProvider } from "@/components/theme-provider";
import { Providers } from "@/components/providers";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={cn("antialiased", geistSans.variable, geistMono.variable, "font-mono", notoNushu.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Providers>
            <AppProvider>
              {children}
            </AppProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
